[package]
name = "double_linked_list_test-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
slotmap = "1"
ascii_table = "4"
stats_alloc = { version = "0.1.10", features = ["nightly"] }
humansize = "2"

[profile.release]
lto = "fat"

[features]
MAKE_INLINE = []
TEST_MODE = []

